import type { Metadata } from "next";
import { ColorModeScript } from "@chakra-ui/react";
import { Inter } from "next/font/google";

// externally crafted imports of resources
import AppProvider from "@/services/AppProvider";
import theme from "@/styles/ChakraTheme";
import NavDrawer from "@/NavDrawer/NavBar";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <NavDrawer />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
